#ifndef GPIO_CONFIG_H
#define GPIO_CONFIG_H

// Sensorar (input)
#define GPIO_WINCH_HOME      CONFIG_GPIO_WINCH_HOME
#define GPIO_WINCH_TENSION   CONFIG_GPIO_WINCH_TENSION
#define GPIO_WINCH_AUTO      CONFIG_GPIO_WINCH_AUTO


// Aktuatorar (output)
#define GPIO_WINCH_DOWN      CONFIG_GPIO_WINCH_DOWN
#define GPIO_WINCH_UP        CONFIG_GPIO_WINCH_UP
#if CONFIG_USE_WINCH_RUNNING_LAMP
#define GPIO_LAMP            CONFIG_GPIO_LAMP
#endif // CONFIG_USE_WINCH_RUNNING_LAMP
#if CONFIG_USE_AUTO_LAMP
#define GPIO_AUTO_LAMP       CONFIG_GPIO_AUTO_LAMP
#endif // CONFIG_USE_AUTO_LAMP
#if CONFIG_USE_ALARM_LAMP
#define GPIO_ALARM_LAMP      CONFIG_GPIO_ALARM_LAMP
#endif // CONFIG_USE_ALARM_LAMP

#endif // GPIO_CONFIG_H